apiVersion: v1
kind: Service
metadata:
  name: modena-rsk
  namespace: modena-rsk
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: modena-rsk
  type: LoadBalancer