version: "3.7"
services:
    modena:
        container_name: modena-composed
        build:
          context: .
          dockerfile: Dockerfile
        extra_hosts:
            - host.docker.internal:host-gateway
        ports: 
            - 6900:3000 #MODENA API port
        environment:
            - DID_METHOD_NAME=modena:bnb
            - CONTENT_ADDRESSABLE_STORE_SERVICE_URI=http://20.121.1.184:5001/
            - DATABASE_NAME=modena-bnb
            - RPC_URL=https://misty-yolo-isle.bsc-testnet.discover.quiknode.pro/9af43ae5b298fc058ae2acce1b6893414e556a8b/
            - MONGO_DB_CONNECTION_STRING=mongodb://host.docker.internal:27017
            - MAX_CONCURRENT_DOWNLOADS=20
            - OBSERVING_INTERVAL_IN_SECONDS=20
            - BATCHING_INTERVAL_IN_SECONDS=40
            - STARTING_BLOCKCHAIN_TIME=27320923
            - BLOCKCHAIN_VERSION=latest
            - MODENA_ANCHOR_CONTRACT=0xa681cA3F5c73D68635d166364F5d214b1270f606
            - WALLET_PRIVATE_KEY=0x253607ef4d9f2ee0c1fe61d42075c78a863dc6e3a6170a9dd4af5ee1a2aa147b
            - LEDGER_TYPE=rsk
