version: "3.7"
services:
    modena:
        container_name: modena-zksync
        image: modena-val:latest
        extra_hosts:
            - host.docker.internal:host-gateway
        ports: 
            - 6900:3000 #MODENA API port
        environment:
            - DID_METHOD_NAME=quarkid:zksync
            - CONTENT_ADDRESSABLE_STORE_SERVICE_URI=http://20.121.1.184:5001/
            - DATABASE_NAME=quarkid-zksync
            - RPC_URL=https://sepolia.era.zksync.dev/
            - MONGO_DB_CONNECTION_STRING=mongodb://host.docker.internal:27017
            - MAX_CONCURRENT_DOWNLOADS=20
            - OBSERVING_INTERVAL_IN_SECONDS=5
            - BATCHING_INTERVAL_IN_SECONDS=10
            - STARTING_BLOCKCHAIN_TIME=2652485
            - BLOCKCHAIN_VERSION=latest
            - MODENA_ANCHOR_CONTRACT=0xd0a16CBeb6da098B872785bFAc282f84F8Ca5993
            - WALLET_PRIVATE_KEY=PEDIMELA
            - ACCOUNT_ADDRESS=0x2535412fA22D9ad83384D7Ab7b636DDA37eFA872
            - LEDGER_TYPE=zksync
    mongo:
      image: mongo:5.0.15
      restart: always
      expose:
        - 27017
      ports:
        - 27017:27017